import type { Metadata } from "next";
import { Encode_Sans_Condensed } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar";
import Footer from "./_components/Footer";
import React from "react";
import "../../node_modules/@fortawesome/fontawesome-free/css/all.min.css";
import NextAuthProviders from "@/Providers/Components/nextauth.providers";
import Providers from "@/Providers/Components/ReactQueryProvider";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';



const Encode = Encode_Sans_Condensed({
  subsets: ["latin"],
  weight: ["300", "400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${Encode.className} antialiased`}>
        <ToastContainer></ToastContainer>
        <Providers>
          <div className="flex flex-col justify-between min-h-screen">
            <NextAuthProviders>
              <Navbar />
              <div className="container mt-14">{children}</div>
              <Footer />
            </NextAuthProviders>
          </div>
        </Providers>
      </body>
    </html>
  );
}
